name = "dosiero"
pages_build_output_dir = "public"
compatibility_date = "2024-06-03"


################################################################################
# B I N D I N G S
################################################################################


# Bind to the Acheron auth system and the dosiero api
services = [
  { binding = "acheron", service = "acheron-auth" },
  { binding = "dosiero", service = "dosiero-api" }
]


################################################################################
# G E N E R A L
################################################################################

[vars]

# The configuration values that should be set when the build command runs on
# deployment (via the rollup configuration).
#
# The rollup build uses the values of the variables to replace textual strings
# into the files that generate.
BUILD_TYPE = "production"
GITHUB_ROOT_URI = "https://github.com/OdatNurd/dosiero"

################################################################################
# A C H E R O N   A U T H   C O N F I G
################################################################################

# Configure the github authentication clientID and client secret to be used
# by Acheron.
#
# These should be distinct from the ones used for development for a variety of
# reasons, not the least of which being that GitHub does not support the notion
# of more than one redirect URL when auth is completed.
github_client_id='Ov23liPW68JQMFvoUhny'
#github_client_secret='sorrynotleakingit'

# The signing secret for JWT tokens that are minted by Acheron after an auth
# request suceeds.
#jwt_secret='sorrynotleakingthiseither'

################################################################################
# D E V   S E R V E R   S E T T I N G S
################################################################################

[dev]
ip = "localhost"
port = 3000
