name = "dosiero"
pages_build_output_dir = "public"
compatibility_date = "2024-06-03"


################################################################################
# G E N E R A L
################################################################################

[vars]


################################################################################
# D E V   S E R V E R   S E T T I N G S
################################################################################

[dev]
ip = "localhost"
port = 3000
