name = "dosiero-api"
main = "src/dosiero.js"
compatibility_date = "2024-06-03"

# Dev versions should have no route; production versions go directly to our
# customized route instead.
#
# Here the zone_id comes from the API section of the overview page of a site in
# the CF Dashboard.
workers_dev = false
routes = [
    { pattern = "dosiero.odatnurd.net/api/*", zone_id="228f86abc5bc8b04719dc4671eb09dc0" },
    { pattern = "dosiero.odatnurd.net/view/*", zone_id="228f86abc5bc8b04719dc4671eb09dc0" }
]


################################################################################
# B I N D I N G S
################################################################################

# Bind our data buckets; the name is specified by you when you create the bucket
# initially.
r2_buckets = [
    { binding = "STORAGE", bucket_name = "dosiero-storage" }
]

# Bind our database; the name and ID come from the D1 page and are visible when
# you create DB or go back to look at one.
[[d1_databases]]
binding = "DB"
database_name = "dosiero"
database_id = "c19bc321-6d52-43ab-b400-a03c7e251607"


################################################################################
# G E N E R A L
################################################################################

[vars]



################################################################################
# D E V   S E R V E R   S E T T I N G S
################################################################################

[dev]
ip = "localhost"
port = 8000


################################################################################
# P R E B U I L D
################################################################################

[build]

# When starting the dev mode server OR when doing a deployment, first execute
# this script, which will generate a file that contains the current commit hash
# for use in the worker code.
command = "node ../tools/getCurrentCommit.js"
