name = "dosiero-api"
main = "src/dosiero.js"
compatibility_date = "2024-06-03"

# Dev versions should have no route; production versions go directly to our
# customized route instead.
#
# Here the zone_id comes from the API section of the overview page of a site in
# the CF Dashboard.
workers_dev = false


################################################################################
# B I N D I N G S
################################################################################


# Bind to the Acheron auth system.
services = [
  { binding = "acheron", service = "acheron-auth" }
]

# Bind to the R2 storage bucket that will contain the contents of uploaded
# dossiers.
r2_buckets = [
    { binding = "storage", bucket_name = "dosiero-storage" }
]

# Bind to the database that will track the application information as a whole.
d1_databases = [
    { binding = "db", database_name = "dosiero", database_id = "c19bc321-6d52-43ab-b400-a03c7e251607"}
]


################################################################################
# G E N E R A L
################################################################################

[vars]

################################################################################
# A C H E R O N   A U T H   C O N F I G
################################################################################

# Configure the github authentication clientID and client secret to be used
# by Acheron.
#
# These should be distinct from the ones used for development for a variety of
# reasons, not the least of which being that GitHub does not support the notion
# of more than one redirect URL when auth is completed.
github_client_id='Ov23liPW68JQMFvoUhny'
#github_client_secret='sorrynotleakingit'

# The signing secret for JWT tokens that are minted by Acheron after an auth
# request suceeds.
#jwt_secret='sorrynotleakingthiseither'


################################################################################
# D E V   S E R V E R   S E T T I N G S
################################################################################

[dev]
ip = "localhost"
port = 8000


################################################################################
# P R E B U I L D
################################################################################

[build]

# When starting the dev mode server OR when doing a deployment, first execute
# this script, which will generate a file that contains the current commit hash
# for use in the worker code.
command = "node ../tools/getCurrentCommit.js"
